# -*- coding: utf-8 -*-
"""Python_Loops_Assignment No 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RFQzlhTVwBDfQF627bULIcT8aGMfdvh

# **Q1:** `for loop` ka use karke 1 se lekar 50 tak saare numbers print karein.
"""

# type your code here
for i in range(1, 51):
    print(i)

"""# **Q2:** `while loop` ka istemal karte hue 10 se 1 tak reverse counting print karein."""

# type your code here
num = 10

while num >= 1:
    print(num)
    num -= 1

"""# **Q3:** User se ek number input lein aur us number ka table (multiplication table) print karein. (e.g., 5 x 1 = 5)"""

# type your code here
num = int(input("Ek number enter karein: "))

for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

"""# **Q4:** 1 se 100 tak ke beech ke saare **Even ** numbers print karein."""

# type your code here
for i in range(1, 101):
    if i % 2 == 0:
        print(i)

"""# **Q5:** Ek list `fruits = ['apple', 'banana', 'cherry', 'date']` di gayi hai. Loop ka use karke har fruit ka naam alag line mein print karein."""

# type your code here
fruits = ['apple', 'banana', 'cherry', 'date']

for fruit in fruits:
    print(fruit)

"""# **Q6:** 1 se lekar 20 tak ke saare numbers ka **Sum** (total) calculate karke

1.   List item
2.   List item

print karein.
"""

# type your code here
total = 0

for i in range(1, 21):
    total += i

print(total)

"""# **Q7:** `while loop` ka use karke user se tab tak numbers input lein jab tak wo `0` enter na karde. End mein saare numbers ka total dikhayein."""

# type your code here
total = 0

while True:
    num = int(input("Number enter karein (0 par stop hoga): "))

    if num == 0:
        break

    total += num

print("Total =", total)

"""# **Q8:** Ek list `numbers = [12, 45, 7, 23, 56, 90, 11]` mein se sabse bada (Maximum) number find karein loop ke zariye."""

# type your code here
numbers = [12, 45, 7, 23, 56, 90, 11]

max_num = numbers[0]

for num in numbers:
    if num > max_num:
        max_num = num

print("Maximum number =", max_num)

"""# **Q9:** User se ek string input lein (e.g., 'Python') aur loop ka use karke us string ko reverse print karein."""

# type your code here
string = input("String enter karein: ")

reversed_string = ""

for i in range(len(string) - 1, -1, -1):
    reversed_string += string[i]

print("Reversed string =", reversed_string)

"""# **Q10:** 1 se 50 tak ke numbers check karein. Agar number 3 se divide hota hai to 'Fizz' print karein, agar 5 se hota hai to 'Buzz' print karein, aur agar dono se hota hai to 'FizzBuzz' print karein."""

# type your code here
for i in range(1, 51):

    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")

    elif i % 3 == 0:
        print("Fizz")

    elif i % 5 == 0:
        print("Buzz")

    else:
        print(i)

"""# **Q11:** Ek list di gayi hai `items = [1, 2, 3, 4, 5]`. Loop ka use karke ek nayi list banayein jis mein har number ka **Square** (e.g., 1, 4, 9...) ho."""

# type your code here
items = [1, 2, 3, 4, 5]

squares = []

for num in items:
    squares.append(num ** 2)

print(squares)

"""# **Q12:** User se ek number lein aur check karein ke wo **Prime Number** hai ya nahi (using loops)."""

# type your code here
num = int(input("Koi number enter karein: "))

if num <= 1:
    print("Prime number nahi hai")
else:
    is_prime = True

    for i in range(2, num):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        print("Prime number hai")
    else:
        print("Prime number nahi hai")

"""# **Q13:** Nested loop ka use karke niche diya gaya pattern print karein:
```
*
**
***
****
*****
```
"""

# type your code here
for i in range(1, 6):
    for j in range(i):
        print("*", end="")
    print()

"""# **Q14:** Multiplication tables print karein 1 se lekar 5 tak (Nested loops use karke)."""

# type your code here
for i in range(1, 6):
    for j in range(1, 11):
        print(f"{i} x {j} = {i * j}")
    print()

"""# **Q15:** Ek list of lists di gayi hai: `matrix = [[1, 2], [3, 4], [5, 6]]`. Nested loop ka use karke saare individual numbers print karein."""

# type your code here
matrix = [[1, 2], [3, 4], [5, 6]]

for row in matrix:
    for num in row:
        print(num)

"""# **Q16:** User se ek number input lein aur us ka **Factorial** find karein (e.g., 5! = 5*4*3*2*1)."""

# type your code here
num = int(input("Koi number enter karein: "))

factorial = 1

for i in range(1, num + 1):
    factorial *= i

print("Factorial =", factorial)

"""# **Q17:** Niche diya gaya pattern print karein:
```
1
12
123
1234
12345
```
"""

# type your code here
for i in range(1, 6):
    for j in range(1, i + 1):
        print(j, end="")
    print()

"""# **Q18:** Ek manual counting karein ke ek string (e.g., 'Learning Python is fun') mein kitne **Vowels** (a, e, i, o, u) hain."""

# type your code here
text = "Learning Python is fun"

vowels = "aeiou"
count = 0

for char in text.lower():
    if char in vowels:
        count += 1

print("Total vowels:", count)

"""# **Q19:** **Fibonacci Sequence** ke pehle 10 numbers print karein (0, 1, 1, 2, 3, 5, 8...)"""

# type your code here
n = 10

a = 0
b = 1

for i in range(n):
    print(a)

    c = a + b
    a = b
    b = c

"""# **Q20:** Ek 'Number Guessing Game' banayein jahan program ek number (1-20) fix kare aur user ko 3 chances de guess karne ke liye. `while loop` aur `break` ka use karein."""

# type your code here
import random

secret_number = random.randint(1, 20)

chances = 3

while chances > 0:
    guess = int(input("1 se 20 tak number guess karein: "))

    if guess == secret_number:
        print("Sahi guess! Aap jeet gaye ")
        break
    else:
        chances -= 1
        print("Galat guess! Bache hue chances:", chances)

if chances == 0:
    print("Game over! Sahi number tha:", secret_number)

